const mongoose=require('mongoose');
const {Schema}=mongoose;

const problemSchema=new Schema({
    problemNumber:{
        type:Number,
        unique:true,
        sparse:true
    },
    title:{
        type:String,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    difficulty:{
        type:String,
        enum:['easy','medium','hard'],
        required:true
    },
    tags:{
        type:String,
        enum:['arrays','strings','dynamic programming','graphs','trees','maths','linkedlists','stacks','queues','hashing','greedy','recursion'],
        required:true   
    },
    visibleTestCases:[
        {
            input:
            {
                type:String,
                required:true
            },
            output:
            {
                type:String,
                required:true
            },
            explanation:
            {
                type:String,    
                required:true
            }
        }
    ],
    hiddenTestCases:[
        {
            input:
            {
                type:String,
                required:true
            },
            output:
            {
                type:String,
                required:true
            }
        }
    ],
    startCode:[
        {
            language:{
                type:String,
                required:true
            },
            initialCode:{
                type:String,
                required:true
            }
        }
    ],
    referenceSolution:[
        {
            language:{
                type:String,
                required:true
            },
            completeCode:{
                type:String,
                required:true
            }
        }
    ],
    problemCreator:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user',
        required:true
    },
    hints:{
        type:[String],
        default:[],
        validate:{
            validator:function(v){
                return Array.isArray(v) && v.length>0;
            },
            message:'At least one hint is required'
        }
    },
    contestId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'contest',
        default:null
    },
    visibleInProblemList:{
        type:Boolean,
        default:true
    },
    removedByAdmin:{
        type:Boolean,
        default:false
    }
})

const Problem=mongoose.model("problem",problemSchema);
module.exports=Problem;
